framework:
    notifier:
        chatter_transports:
        texter_transports:
            brevo: '%env(BREVO_DSN)%'
        channel_policy:
            urgent: ['sms']
            high: ['sms']
            medium: ['email']
            low: ['email']
        admin_recipients:
            - { email: admin@farmoms.app }